version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DATABASE_NAME: fastapi_app
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data: